---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices-demo-big-nodes
resources:
- namespace.yaml
- ../bases/microservices-demo
components:
- ../components/node-selector-big
- ../components/google-cloud-operations
